micronaut:
  application:
    name: micronautTodo
  server:
    cors:
      enabled: true

datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5432/postgres?user=niravchavda&password=niravchavda`}
    driverClassName: org.postgresql.Driver
    dialect: POSTGRES
    packages-to-scan:
      - 'com.incubyte'
jpa:
  default:
    properties:
      hibernate:
        show_sql: true
liquibase:
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.sql'