micronaut:
  application:
    name: micronautTodo
  server:
    cors:
      enabled: true

datasources:
  default:
    #    url: jdbc:h2:mem:devDb
    #    driverClassName: org.h2.Driver
    #    url: jdbc:postgresql://localhost:49153/postgres
    url: ${DB_URL:`jdbc:postgresql://localhost:49153/postgres?user=postgres&password=postgrespw`}
    driverClassName: org.postgresql.Driver
    #    username: postgres
    #    password: postgrespw
    #    schema-generate: CREATE_DROP
    #    dialect: H2
    dialect: POSTGRES
    packages-to-scan:
      - 'com.incubyte'
jpa:
  default:
    properties:
      hibernate:
        #        hbm2ddl:
        #          auto: update
        show_sql: true
liquibase:
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.sql'