micronaut:
  application:
    name: micronautTodo

datasources:
  default:
#    url: jdbc:h2:mem:devDb
#    driverClassName: org.h2.Driver
    url: jdbc:mysql://localhost:3306/db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
#    schema-generate: CREATE_DROP
#    dialect: H2
#    dialect: MYSQL
    packages-to-scan:
      - 'com.incubyte'
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
liquibase:
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.sql'